### ISSUE TITLE
Project Hoodie

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#54]
Let us create a high-quality hoodie for OpenSustain.tech Contributors.

Milestones:
* Motivate People that have already contributed by sending them a hoodie
* Give new contributors a hoodie
* Give contributors of the listed projects a hoodie, like Hacktoberfest  

Task:
* Research for Hoodies and Manufactures:
   * https://www.neutral.com/
   * Ask FSFE for possible ways to do the sending of hoodies. (Tobi)
* Ask Designer for OpenSustain.tech Hoodie
   * Miriam
   * https://tabletopwhale.com/
   * https://discourse.opensourcedesign.net/
   * ....
* Ask OST contributors for feedback on different designs

**Comment by tjarkdoering** [comment]
Since the first batch of hoodies will come from Germany, I looked for a few sources from here.
A secondary requirement could be the absence of any branding.

* [grundstoff.net](https://www.grundstoff.net/maenner/sweatjacken/?p=1): 100 % bio cotton, no branding, affordable ~ 50 €
* [recolution](https://www.recolution.de/maenner/herbst-_-winterkollektion/basic-sweatjacket-dark-eukalyptus-l): vegan and GOTS certification, not many colors, ~ 80 €
* [zuendstoff.basics](https://www.zuendstoff-clothing.de/Marken/Produkte/zuendstoff-basics/id/83e49b8d-8f51-c448-97f4-89a40cc6ea83): GOTS, not many colors, affordable ~ 50 €
* [fuxbau](https://fuxbau.de/produkt/unisex-fux-hoodie-navy/): bio, fair, sustainable, not man colors, 80 €
* [PHYNE](https://phyne.com/collections/maenner-hoodies): Three "colors", expensive > 80 €
* [bleed](https://www.bleed-clothing.com/deutsch/shop-herren/hoodies-zip-hoodies): simple colors, vegan, bio cotton, fair production, ~80 €
* [KUYICHI](https://kuyichi.com/collections/sweaters): bio cotton, not many colors, ~ 90 €

**Comment by tjarkdoering** [comment]
Idea: Add a pull request template to the contribution guide and give people the option the choose between planting trees or getting a hoodie.
